function build_simulink_model()
%BUILD_SIMULINK_MODEL Builds a Simulink model for momentum-only plant:
% xdot = tau_ext - [B]_x*m

model = "mtq_desat_mpc_model";
if bdIsLoaded(model); close_system(model,0); end
new_system(model); open_system(model);

% Basic layout positions
x0 = 40; y0 = 40; dx = 180; dy = 80;

% Blocks
add_block("simulink/Sources/Clock", model+"/Clock", "Position",[x0 y0 x0+60 y0+30]);
add_block("simulink/User-Defined Functions/MATLAB Function", model+"/B_field", ...
    "Position",[x0+dx y0 x0+dx+120 y0+60]);
add_block("simulink/User-Defined Functions/MATLAB Function", model+"/Tau_ext", ...
    "Position",[x0+dx y0+dy x0+dx+120 y0+dy+60]);

add_block("simulink/User-Defined Functions/MATLAB Function", model+"/Controller", ...
    "Position",[x0+2*dx y0+0.5*dy x0+2*dx+140 y0+0.5*dy+90]);

add_block("simulink/Math Operations/Gain", model+"/TsGain", ...
    "Gain","Ts", "Position",[x0+3*dx y0+0.5*dy x0+3*dx+60 y0+0.5*dy+50]);

add_block("simulink/Continuous/Integrator", model+"/Int_x", ...
    "Position",[x0+4*dx y0+0.5*dy x0+4*dx+60 y0+0.5*dy+60]);

add_block("simulink/Sinks/To Workspace", model+"/x_log", ...
    "VariableName","x_log", "SaveFormat","StructureWithTime", ...
    "Position",[x0+5*dx y0+0.5*dy x0+5*dx+100 y0+0.5*dy+60]);

add_block("simulink/Sinks/To Workspace", model+"/m_log", ...
    "VariableName","m_log", "SaveFormat","StructureWithTime", ...
    "Position",[x0+3*dx y0+1.4*dy x0+3*dx+100 y0+1.4*dy+60]);

% Sum: tau_ext + tau_mtq
add_block("simulink/Math Operations/Sum", model+"/SumTau", ...
    "Inputs","++", "Position",[x0+3*dx y0+0.5*dy-40 x0+3*dx+40 y0+0.5*dy]);

% tau_mtq = -[B]_x*m implemented in MATLAB Function "MTQ_Torque"
add_block("simulink/User-Defined Functions/MATLAB Function", model+"/MTQ_Torque", ...
    "Position",[x0+2.5*dx y0+1.4*dy x0+2.5*dx+140 y0+1.4*dy+90]);

% Wire connections
add_line(model,"Clock/1","B_field/1");
add_line(model,"Clock/1","Tau_ext/1");

add_line(model,"Int_x/1","Controller/1");     % x -> controller
add_line(model,"B_field/1","Controller/2");   % B -> controller

add_line(model,"Controller/1","m_log/1");     % log m
add_line(model,"Controller/1","MTQ_Torque/1");% m -> mtq torque
add_line(model,"B_field/1","MTQ_Torque/2");   % B -> mtq torque

add_line(model,"Tau_ext/1","SumTau/1");       % tau_ext
add_line(model,"MTQ_Torque/1","SumTau/2");    % tau_mtq

add_line(model,"SumTau/1","TsGain/1");
add_line(model,"TsGain/1","Int_x/1");
add_line(model,"Int_x/1","x_log/1");

% Set model variables
set_param(model,"StopTime","Tend");
set_param(model,"Solver","ode4","FixedStep","Ts");

% Fill MATLAB Function blocks
set_param(model+"/B_field","Script", ...
"function B = fcn(t)\n" + ...
"%#codegen\n" + ...
"persistent P;\n" + ...
"if isempty(P); P = evalin('base','P'); end\n" + ...
"k = floor(t/P.Ts)+1;\n" + ...
"B = orbit_propagator_simple(k, P);\n" + ...
"end\n");

set_param(model+"/Tau_ext","Script", ...
"function tau = fcn(t)\n" + ...
"%#codegen\n" + ...
"persistent P;\n" + ...
"if isempty(P); P = evalin('base','P'); end\n" + ...
"k = floor(t/P.Ts)+1;\n" + ...
"tau = ext_torques(k, P);\n" + ...
"end\n");

set_param(model+"/MTQ_Torque","Script", ...
"function tau_mtq = fcn(m, B)\n" + ...
"%#codegen\n" + ...
"tau_mtq = cross(m, B);\n" + ...
"end\n");

set_param(model+"/Controller","Script", ...
"function m = fcn(x, B)\n" + ...
"%#codegen\n" + ...
"persistent P m_prev step;\n" + ...
"if isempty(P)\n" + ...
"  P = evalin('base','P');\n" + ...
"  m_prev = zeros(3,1);\n" + ...
"  step = 1;\n" + ...
"end\n" + ...
"\n" + ...
"% Choose controller here:\n" + ...
"mode = 'mpc'; % 'baseline' or 'mpc'\n" + ...
"\n" + ...
"if strcmp(mode,'baseline')\n" + ...
"  m = baseline_mtq(x, B, P);\n" + ...
"else\n" + ...
"  % Use internal step counter for prediction index.\n" + ...
"  Bprov   = @(kk) orbit_propagator_simple(kk, P);\n" + ...
"  tauprov = @(kk) ext_torques(kk, P);\n" + ...
"  m = mpc_mtq_qp(x, step, P, Bprov, tauprov, m_prev);\n" + ...
"end\n" + ...
"\n" + ...
"m_prev = m;\n" + ...
"step = step + 1;\n" + ...
"end\n");

save_system(model);
disp("Built Simulink model: " + model + ".slx");
end
